spring:
  application:
    name: maven-base
  messages:
    encoding: UTF-8
  jackson:
    time-zone: "Asia/Tokyo"
  datasource:
    driver-class-name: org.h2.Driver
    url: dbc:h2:mem:;
    username: sa
    password: 
  h2:
    console:
      enabled: true  
    
logging:
  level:
    web: debug    
    
